library(jsonlite)
library(httpuv)
library(httr)
oauth_endpoints('github')
myapp <- oauth_app("github","token", secret = "sectrot")
github_token <- oauth2.0_token(oauth_endpoints("github"), myapp)
sig <- sign_oauth2.0(myapp, "token")
req <- GET("https://api.github.com/users/jtleek/repos", sig)

myjson <- content(req)
myjson2 <- jsonlite::fromJSON(toJSON(myjson))
View(myjson2)
stop_for_status(req)
content(req)
